### ISSUE TITLE
As a [teammate] I want to [auto-publish the SQLPROJ using CICD] so [the shared DB reflects the code base].

### ISSUE THREAD

**Issue by ar2525** [MsCornell/2425Repo#11]
## Acceptance Criteria

- [x] `./database/Database.sqlproj` is source
- [x] Azure SQL DB is target
- [ ] Trigger is `[push]`

## Tasks

- [x] Ensure target database platform
- [x] Ensure SQLPROJ builds properly
- [x] Create `./github/workflows/database.yml`
- [x] Implement [sql-action](https://github.com/azure/sql-action?tab=readme-ov-file#build-and-deploy-a-sql-project)
- [x] Introduce repository secret
- [x] Test & validate workflow
- [ ] Change to use `[push]`
