### ISSUE TITLE
As [Project Manager], I want to create a milestone for user authentication.

### ISSUE THREAD

**Issue by ar2525** [MsCornell/2425Repo#13]
### Acceptance Criteria:
- [ ] Discuss with team members how we want the authentication flow to look.
- [ ] Implement rudimentary pieces of user authentication (storing a username/password in the database, and being able to access that username/password for verification purposes)
- [ ] Decide on scope of user authentication --- do we want to set up a basic system now and expand on it later? Or put more effort into the game itself?
