### ISSUE TITLE
As [player], I want to [play Ultra Tic Tac Toe against an AI opponent] so that [I can practice and improve my skills].

### ISSUE THREAD

**Issue by RichardCGL** [MsCornell/2425Repo#134]
### Assignment Criteria:
- [ ] There will be an AI opponent to play against.

### Tasks
- [ ] Plan out the ML model that we will use.
- [ ] Train the model on how to play Ultimate Tic-Tac-Toe.
- [ ] Link the model with the actual game and its interface.
