### ISSUE TITLE
As [player], I [want to know if one cell of the board has been won, and by whom].

### ISSUE THREAD

**Issue by ar2525** [MsCornell/2425Repo#15]
### Acceptance Criteria
- [ ] A unique mark should be shown if a player wins in a small section.
 
### Tasks
- [x] Display visually when a board has been won
- [x] Do not allow changes to be made to a won board.
