### ISSUE TITLE
As a [user], I want to be able to [save my progress to my account].

### ISSUE THREAD

**Issue by ar2525** [MsCornell/2425Repo#16]
### Acceptance Criteria: 
- [ ] Users' data should be collected and stored.
- [ ] Users' data should be linked to the account.

### Tasks
- [ ] Keep track of the outcome of a game in the database, then link that progress to the user.
