### ISSUE TITLE
Prompt for login from two players when playing local multiplayer

### ISSUE THREAD

**Issue by ar2525** [MsCornell/2425Repo#34]
- [ ] After logging in, prompt user if they want to play against AI or local multiplayer
- [ ] If they click local multiplayer, prompt for a second login
- [ ] Assign each login to an X or O; record moves accordingly

### Tasks

- [ ] Make another page after login to prompt for local multiplayer, both in the mockup and the actual code
