### ISSUE TITLE
As a [new user], I want to [create an account]

### ISSUE THREAD

**Issue by ar2525** [MsCornell/2425Repo#36]
### Acceptance Criteria
- [ ] Know what is the sign in information(password, name, account
- [ ] Users should be able to create a new account
- [ ] Backend should be able to store the account and related information
- [ ] Users should be able to choose their unique name and password for their account.
- [ ] If the name is duplicated, the player cannot choose it and a warning must be shown.

### Tasks

- [ ] Create back-end interface to store user's information
- [ ] Have back-end check for duplicates
