### ISSUE TITLE
As a [player], I hope there is [a clear sign telling me what to do].

### ISSUE THREAD

**Issue by ar2525** [MsCornell/2425Repo#37]
### Acceptance Criteria
- [ ] There should be a sign telling player to wait or to draw
- [ ] Where player is able to draw should be displayed
- [ ] There should be a sign/visual indicator telling player whose turn it is.

### Tasks
- [ ] Create visual interface to show where players can draw.
- [ ] Display visually whose turn it is
- [ ] Prevent player from drawing on a turn that isn't theirs.
