### ISSUE TITLE
As [user], I [want to sign up for an account].

### ISSUE THREAD

**Issue by ar2525** [MsCornell/2425Repo#42]
###Tasks

- [x] Make and implement page for signup process
- [x] Link the signup to the database
- [x] Set up database for account information and each game data.
