### ISSUE TITLE
As [user], I hope [my game history is stored correctly with my account].

### ISSUE THREAD

**Issue by ar2525** [MsCornell/2425Repo#46]
### Tasks

- [ ] Store a user’s wins and losses
- [ ] Calculate a score for a given user based on their wins and losses—this is what will be used to rank them on the leaderboard
- [ ] Add a field to hold wins, losses, and scores in the database for a particular user
