### ISSUE TITLE
As [user], I [want to quit the game].

### ISSUE THREAD

**Issue by ar2525** [MsCornell/2425Repo#48]
### Tasks:

- [x] Add button w/ on click function that returns to home page
- [x] Text for button should say “Quit” or “Return to Homepage” or something similar
- [ ] On click, have an “are you sure?” prompt to make sure the user doesn’t accidentally click out of the game
- [ ]
