### ISSUE TITLE
As [user], I want [the database to record the whole game play].

### ISSUE THREAD

**Issue by ar2525** [MsCornell/2425Repo#49]
### Tasks:

- [ ] Each time a new game is started, create a new instance of a table for this game
- [ ] For each move, mark the according table in the database
- [ ]      Should this happen during the game or at the end of the game?
- [ ] Store a user’s wins and losses
- [ ] Calculate a score for a given user based on their wins and losses—this is what will be used to rank them on the leaderboard
- [ ] Add a field to the user table to hold wins, losses, and scores in the database for a particular user
