### ISSUE TITLE
As [user], I want to have a leaderboard to check my rank.

### ISSUE THREAD

**Issue by ar2525** [MsCornell/2425Repo#50]
### Tasks

- [ ] In the Blazor section, add a button where the onClick function takes you to back to the homepage from the leaderboard page
- [ ] Make a page for the leaderboard
- [ ] Link to the leaderboard page from somewhere else—could be the game board page, the homepage, or both
