### ISSUE TITLE
As [player], I want to [be prompted to play against another user or AI] and [only log in once].

### ISSUE THREAD

**Issue by ar2525** [MsCornell/2425Repo#53]
### Tasks

- [ ] Make another page to handle the "are you playing against another person or an AI"
- [ ] Make sure this page leads to the game after logging in
- [ ] Decide if logging in will happen before or after a selection is made (probably before?)
